server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #开启动态路由后，uri后面接的是服务名称
          # 这里注意了，开启动态路由之后的uri的写法是：lb://serviceName,lb是协议，表示启用Gateway的负载均衡功能
          #，lb://serviceName是springcloud gateway在微服务中自动为我们创建的负载均衡uri
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            #- After=2020-04-24T21:48:46.985+08:00[Asia/Shanghai],指定在某个时间之后才能访问
            #- Before=2020-04-24T21:48:46.985+08:00[Asia/Shanghai]，指定某个时间之前才能访问
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
            # 上述是路由规则，Gateway路由规则很多，访问官网查看
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/